import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "@mantine/core/styles.css";
import "@mantine/carousel/styles.css";
import {
  MantineProvider,
  ColorSchemeScript,
  Container,
  Space,
  Box,
} from "@mantine/core";
import { HeaderSimple } from "./components/ui/header/simpleMenu";
import { FooterSimple } from "./components/ui/footer/simpleFooter";

const font = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={font.className}>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider>
          <Container>
            <Space h={"lg"} />
            <HeaderSimple />
            <Box mih="100vh">{children}</Box>
            <FooterSimple />
          </Container>
        </MantineProvider>
      </body>
    </html>
  );
}
